[General]
passwordCharacter=*
passwordMask=true
passwordInputWidth=0.5
passwordInputBackground=
passwordInputRadius=
passwordInputCursorVisible=false
passwordFontSize=72
passwordCursorColor=random
passwordTextColor=
passwordAllowEmpty=false
cursorBlinkAnimation=true
showSessionsByDefault=false
sessionsFontSize=24
showUsersByDefault=false
usersFontSize=48
showUserRealNameByDefault=true
background=yuna_small.jpg
backgroundFill=#000000
backgroundFillMode=aspect
basicTextColor=#ffffff
blurRadius=0
hideCursor=true
font=monospace
helpFont=monospace
helpFontSize=18
